export const USER = 'User'
export const ROLE = 'Role'
export const GIAOVIEN = 'GiaoVien'
export const SINHVIEN = 'SinhVien'
export const NHATKY = 'NhatKy'
export const THONGBAO = 'ThongBao'
export const DETAI = 'DeTai'
export const BOMON = 'BoMon'
export const KHOAHOC = 'KhoaHoc'
export const LOPHOC = 'LopHoc'
export const DIADIEMTHUCTAP = 'DiaDiemThucTap'
export const NAMHOC = 'NamHoc'
export const LINHVUC = 'LinhVuc'
export const TUKHOA = 'TuKhoa'
export const NGACHGIANGVIEN = 'NgachGiangVien'
export const KEHOACHTT = 'KeHoachTT'
export const KEHOACH_CHITIET = 'KeHoachChiTiet'
export const DANHSACHTHUCTAP = 'DanhSachThucTap'
export const DOTTHUCTAP = 'DotThucTap'
export const NHIEMVUSINHVIEN = 'NhiemVuSinhVien'
export const DANGKYTHUCTAP = 'DangKyThucTap'
export const NHOMTHUCTAP = 'NhomThucTap'
export const CHITIET_NHOMTHUCTAP = 'ChiTietNhomThucTap'
export const FILE = 'File'



